
server:
  port: 8762

spring:
  application:
    name: Config-Server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/purvanshsharma618/Config_Server
          clone-on-start: true
